### PR TITLE
Event display

### PR DESCRIPTION
**Pull request by 153957**
A real-time event display for coincidences (and possibly events).
Size of the circles indicate the number of MIPs.

Preview: http://bl.ocks.org/davidfokkema/dbb46151127086dccec2

### CODE REVIEW

**Comment by 153957** [comment]
Looking good!

**Comment by davidfokkema** [comment]
Thanks! How did you figure out the preview? I was about to post it, ;-)

**Comment by 153957** [comment]
Your commit mentioned bl.ocks.org , so I looked there, it mentioned Gists, so I checked your gists, saw that you had something there about visualization, went to bl.ocks.org/davidfokkema and clicked the Gist about visualization.

**Comment by davidfokkema** [comment]
Exactly!

**Comment by 153957** [comment]
Due date: 24 March :wink: 

On the 24th @vaneijk will give a talk during the Topical Lectures (Cosmic Rays) about HiSPARC.
It would be nice if he could show such a real-time display (for coincidences and/or events).

**Comment by davidfokkema** [comment]
Challenge accepted! It would indeed be very nice to have it working by then. Let's take a look Monday and figure out what still needs to be done, or what needs to be changed.

**Comment by 153957** [comment]
Perhaps use cleaner (no labels) map tiles?
http://bl.ocks.org/153957/ed0a88eff6be42483043

**Comment by davidfokkema** [comment]
I really like the subdued colors. Not (yet) sure about the labels, though.

**Comment by 153957** [comment]
Ok, they also have one with labels:
http://bl.ocks.org/153957/ed0a88eff6be42483043/c5dab9ab55816655c7f798bc81fc3062042c277c

haha, 'science park' everywhere!

**Comment by davidfokkema** [comment]
Yes! I like that one.

**Comment by 153957** [comment]
Also works for data from the entire network!
Awesome!

network_events

**Comment by davidfokkema** [comment]
Very, very nice!

**Pull request merged**
